# Homebrew packages for macOS, installed with `brew bundle install --no-upgrade`
# by scripts/bootstrap-macos.sh and run_onchange_before_12-install-homebrew-packages.sh.tmpl.
# Project-specific toolchains stay in each project's own setup docs.

brew "actionlint"
brew "ca-certificates"
brew "cloudflared"
brew "colima"
brew "curl"
brew "docker"
brew "docker-buildx"
brew "docker-compose"
brew "fd"
brew "ffmpeg"
brew "fish"
brew "gh"
brew "git"
brew "gnupg"
brew "jq"
brew "opentofu"
brew "pandoc"
brew "pkgconf"
brew "ripgrep"
brew "tmux"
brew "treemd"
brew "unzip"
brew "xz"
brew "ykman"

cask "anki"
cask "brave-browser"
cask "font-comic-shanns-mono-nerd-font"
cask "google-chrome"
cask "google-japanese-ime"
cask "iina"
cask "intellij-idea"
cask "karabiner-elements"
cask "obs"
cask "raycast"
cask "slack"
cask "wezterm"
