set -g @layout_pc 'd9d8,76x43,0,0[76x21,0,0{38x21,0,0,0,37x21,39,0,3},76x21,0,22{38x21,0,22,1,37x21,39,22[37x10,39,22,2,37x10,39,33,4]}]'

set-option -g default-terminal screen-256color
set -g terminal-overrides 'xterm:colors=256'

set -g prefix C-f
unbind C-b

set-option -g status-position top
set-option -g status-left-length 90
set-option -g status-right-length 90
set-option -g status-left '#H:[#P]'
set-option -g status-right '[%Y-%m-%d(%a) %H:%M]'
set-option -g status-interval 1
set-option -g status-justify centre
set-option -g status-bg "colour238"
set-option -g status-fg "colour255"

bind C-h select-pane -L
bind C-j select-pane -D
bind C-k select-pane -U
bind C-l select-pane -R

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

unbind C-Left
unbind C-Right
unbind C-Up
unbind C-Down
unbind Left
unbind Right
unbind Up
unbind Down
unbind M-b
unbind M-f

bind -r C-Left swap-pane -d -s :. -t '{left-of}'
bind -r C-Right swap-pane -d -s :. -t '{right-of}'
bind -r C-Up swap-pane -d -s :. -t '{up-of}'
bind -r C-Down swap-pane -d -s :. -t '{down-of}'

bind | split-window -h
bind - split-window -v

set-option -g base-index 1
set-option -g mouse on
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'copy-mode -e'"
bind-key -n WheelDownPane select-pane -t= \; send-keys -M

setw -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi V send -X select-line
bind -T copy-mode-vi C-v send -X rectangle-toggle
bind -T copy-mode-vi y send -X copy-selection
bind -T copy-mode-vi Y send -X copy-line

bind-key C-n new-window -n copy "tmux capture-pane -t ! -pS -32768 | nvim -; tmux kill-window"
bind-key C-p display-popup -E "fish"

if-shell "uname -a | grep -q Microsoft" '\
  bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "clip.exe"; \
  bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "clip.exe"; \
  bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "clip.exe"\
'

set -g focus-events on
set-hook -g pane-focus-in 'run-shell -b "zoom=\$(tmux display-message -p \"#{window_zoomed_flag}\"); [ \"\$zoom\" = 0 ] || exit 0; no=\$(tmux show-option -pqv @no_auto_zoom); [ -z \"\$no\" ] || exit 0; tty=\$(tmux display-message -p \"#{pane_tty}\"); cmd=\$(ps -o comm= -t \${tty#/dev/} 2>/dev/null | tail -n 1); case \"\$cmd\" in nvim|vim) tmux resize-pane -Z ;; esac"'

unbind !
bind-key ! break-pane -d -n _hidden_pane
bind-key @ join-pane -s $.0

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'tmux-plugins/tmux-urlview'

if-shell 'test -x ~/.tmux/plugins/tpm/tpm' 'run ~/.tmux/plugins/tpm/tpm'
